# Generated by Django 6.0.2 on 2026-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.IntegerField(default=80, help_text='Minimum confidence to trigger an alert.')),
                ('auto_block_severity', models.CharField(choices=[('High', 'High Only'), ('Medium', 'Medium & High'), ('All', 'All Detected Attacks')], default='High', max_length=20)),
            ],
        ),
    ]
