# Generated by Django 6.0.2 on 2026-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global switch to activate or deactivate the detection system.'),
        ),
    ]
