# Generated by Django 6.0.2 on 2026-03-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_systemsetting_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_processed', models.BigIntegerField(default=0)),
                ('total_attacks', models.BigIntegerField(default=0)),
                ('blocked_ips', models.BigIntegerField(default=0)),
            ],
        ),
    ]
